#!/usr/bin/python3
import sys
           　　 

def tonum(s):
             try: 
                 ans += int(s)   #intは文字列を整数に（失敗すると例外発生）
             except:
                 ans += float(s)
                                                          　 
ans = 0
for line in sys.stdin:
    line = line.resrip()
    ans += tonum(line)

